// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilkCollector.API.Data;

#nullable disable

namespace MilkCollector.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("MilkCollector.API.Models.Entities.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FarmerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FatReading")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Liters")
                        .HasColumnType("TEXT");

                    b.Property<long?>("MilkAmountPaise")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("FarmerId", "CollectionDate", "Shift")
                        .IsUnique();

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.Farmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Farmers");
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.FarmerFatKindSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<int>("FarmerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId");

                    b.HasIndex("UserId");

                    b.ToTable("FarmerFatKindSegments");
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.FatRateRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("RateKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("RupeesPerFatPointPerLiterPaise")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FatRateRules");
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.LedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountPaise")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FarmerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SettlementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId");

                    b.ToTable("LedgerEntries");
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$67mgVTZJs3aFX4TSCLOumuUNOi.q0cnoVjjoFHso2SQ.MNiWBNTJO",
                            Role = "manager",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.PashuAahar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FarmerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PaidPaise")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PashuAaharName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PricePaise")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecordedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId");

                    b.ToTable("PashuAahars");
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.Settlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settlements");
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.SettlementLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FarmerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LedgerNetPaise")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MilkAmountPaise")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NetPayablePaise")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PaidAmountPaise")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentNote")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentRecordedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("SettlementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId");

                    b.HasIndex("SettlementId");

                    b.ToTable("SettlementLines");
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.Collection", b =>
                {
                    b.HasOne("MilkCollector.API.Models.Entities.Farmer", "Farmer")
                        .WithMany("Collections")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilkCollector.API.Models.Entities.User", null)
                        .WithMany("Collections")
                        .HasForeignKey("UserId");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.FarmerFatKindSegment", b =>
                {
                    b.HasOne("MilkCollector.API.Models.Entities.Farmer", "Farmer")
                        .WithMany("FatKindSegments")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilkCollector.API.Models.Entities.User", null)
                        .WithMany("FarmerFatKindSegments")
                        .HasForeignKey("UserId");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.LedgerEntry", b =>
                {
                    b.HasOne("MilkCollector.API.Models.Entities.Farmer", "Farmer")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.PashuAahar", b =>
                {
                    b.HasOne("MilkCollector.API.Models.Entities.Farmer", "Farmer")
                        .WithMany("PashuAahars")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.SettlementLine", b =>
                {
                    b.HasOne("MilkCollector.API.Models.Entities.Farmer", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilkCollector.API.Models.Entities.Settlement", "Settlement")
                        .WithMany("Lines")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.Farmer", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("FatKindSegments");

                    b.Navigation("LedgerEntries");

                    b.Navigation("PashuAahars");
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.Settlement", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MilkCollector.API.Models.Entities.User", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("FarmerFatKindSegments");
                });
#pragma warning restore 612, 618
        }
    }
}
